import Head from 'next/head'
import PhoneCompo from '../components/PhoneCompo'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Phone Component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PhoneCompo/>

    </div>
  )
}
